/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedTrackerRouteImport } from './routes/_authenticated/tracker'
import { Route as ApiPublicBeaconRouteImport } from './routes/api/public/beacon'
import { Route as ApiPublicBeaconEnrollRouteImport } from './routes/api/public/beacon-enroll'
import { Route as ApiPublicBeaconEnrollStatusRouteImport } from './routes/api/public/beacon-enroll-status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrackerRoute = AuthenticatedTrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicBeaconRoute = ApiPublicBeaconRouteImport.update({
  id: '/api/public/beacon',
  path: '/api/public/beacon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBeaconEnrollRoute = ApiPublicBeaconEnrollRouteImport.update({
  id: '/api/public/beacon-enroll',
  path: '/api/public/beacon-enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBeaconEnrollStatusRoute =
  ApiPublicBeaconEnrollStatusRouteImport.update({
    id: '/api/public/beacon-enroll-status',
    path: '/api/public/beacon-enroll-status',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/download': typeof DownloadRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/tracker': typeof AuthenticatedTrackerRoute
  '/api/public/beacon': typeof ApiPublicBeaconRoute
  '/api/public/beacon-enroll': typeof ApiPublicBeaconEnrollRoute
  '/api/public/beacon-enroll-status': typeof ApiPublicBeaconEnrollStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/download': typeof DownloadRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/tracker': typeof AuthenticatedTrackerRoute
  '/api/public/beacon': typeof ApiPublicBeaconRoute
  '/api/public/beacon-enroll': typeof ApiPublicBeaconEnrollRoute
  '/api/public/beacon-enroll-status': typeof ApiPublicBeaconEnrollStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/download': typeof DownloadRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/tracker': typeof AuthenticatedTrackerRoute
  '/api/public/beacon': typeof ApiPublicBeaconRoute
  '/api/public/beacon-enroll': typeof ApiPublicBeaconEnrollRoute
  '/api/public/beacon-enroll-status': typeof ApiPublicBeaconEnrollStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/download'
    | '/admin'
    | '/tracker'
    | '/api/public/beacon'
    | '/api/public/beacon-enroll'
    | '/api/public/beacon-enroll-status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/download'
    | '/admin'
    | '/tracker'
    | '/api/public/beacon'
    | '/api/public/beacon-enroll'
    | '/api/public/beacon-enroll-status'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/download'
    | '/_authenticated/admin'
    | '/_authenticated/tracker'
    | '/api/public/beacon'
    | '/api/public/beacon-enroll'
    | '/api/public/beacon-enroll-status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DownloadRoute: typeof DownloadRoute
  ApiPublicBeaconRoute: typeof ApiPublicBeaconRoute
  ApiPublicBeaconEnrollRoute: typeof ApiPublicBeaconEnrollRoute
  ApiPublicBeaconEnrollStatusRoute: typeof ApiPublicBeaconEnrollStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tracker': {
      id: '/_authenticated/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof AuthenticatedTrackerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/beacon': {
      id: '/api/public/beacon'
      path: '/api/public/beacon'
      fullPath: '/api/public/beacon'
      preLoaderRoute: typeof ApiPublicBeaconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/beacon-enroll': {
      id: '/api/public/beacon-enroll'
      path: '/api/public/beacon-enroll'
      fullPath: '/api/public/beacon-enroll'
      preLoaderRoute: typeof ApiPublicBeaconEnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/beacon-enroll-status': {
      id: '/api/public/beacon-enroll-status'
      path: '/api/public/beacon-enroll-status'
      fullPath: '/api/public/beacon-enroll-status'
      preLoaderRoute: typeof ApiPublicBeaconEnrollStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedTrackerRoute: typeof AuthenticatedTrackerRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedTrackerRoute: AuthenticatedTrackerRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DownloadRoute: DownloadRoute,
  ApiPublicBeaconRoute: ApiPublicBeaconRoute,
  ApiPublicBeaconEnrollRoute: ApiPublicBeaconEnrollRoute,
  ApiPublicBeaconEnrollStatusRoute: ApiPublicBeaconEnrollStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
